# Generated by Django 4.2.11 on 2024-05-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_coin_trade_portfolio_alter_trade_holding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='holding',
        ),
    ]
