# Generated by Django 4.2.11 on 2024-05-10 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_trade_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
