# Generated by Django 4.2.11 on 2024-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
